/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Db": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GOOGLE_MAPS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SendEmail": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}