/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "Db": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GOOGLE_MAPS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MediaBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "OPENWEBNINJA_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SendEmail": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "addEventToDBFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "clockoutdcTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "dccomedyloftTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "dcimprovTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "eventbriteTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "hi": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "normaizeEventStepFunction": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "normalizeEventFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "user_analytics": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "washingtonianTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}