name: Deploy and Seed Data

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd packages/scripts && npm install

      - name: Setup SST environment and run deployment tasks
        run: |
          npx sst deploy --stage production
          npx sst shell --stage production -- bash -c "
            cd packages/scripts && npm install &&
            cd ../.. &&
            npx tsx packages/scripts/src/seed-data.ts &&
            npx tsx packages/scripts/src/seed-groups.ts &&
            cd packages/scripts &&
            npm run migrate:opensearch
          "
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
